services:
  - type: worker
    name: telegram-cloner-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    autoDeploy: true
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: SESSION_NAME
        defaultValue: "session"
      - key: SOURCE_USERNAME
        sync: false
      - key: TARGET_USERNAME
        sync: false
